# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags like v1.0.0, v0.1.2, etc.

permissions:
  contents: write # Needed to create releases

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23' # Specify your Go version

      # Install musl-tools for static linux builds if you need them
      # sudo apt-get update && sudo apt-get install -y musl-tools
      # If you are not building for linux/musl, you can remove this.
      - name: Install musl-tools for static Linux builds
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest # You can also pin to a specific GoReleaser version
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}